/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as ManualsRouteImport } from './routes/manuals'
import { Route as CocktailsRouteImport } from './routes/cocktails'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesIndexRouteImport } from './routes/updates.index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as RecentIndexRouteImport } from './routes/recent.index'
import { Route as QaIndexRouteImport } from './routes/qa.index'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as ManualsIndexRouteImport } from './routes/manuals.index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as EmployeeWorkIndexRouteImport } from './routes/employee-work.index'
import { Route as EmployeeLoginIndexRouteImport } from './routes/employee-login.index'
import { Route as CocktailsIndexRouteImport } from './routes/cocktails.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ManualsIdRouteImport } from './routes/manuals.$id'
import { Route as EmployeeWorkIdRouteImport } from './routes/employee-work.$id'
import { Route as CocktailsIdRouteImport } from './routes/cocktails.$id'
import { Route as AboutIdRouteImport } from './routes/about.$id'
import { Route as RulesCategoryIdRouteImport } from './routes/rules.category.$id'
import { Route as ApiNotionImageBlockIdRouteImport } from './routes/api/notion-image.$blockId'
import { Route as AboutCategoryIdRouteImport } from './routes/about.category.$id'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsRoute = ManualsRouteImport.update({
  id: '/manuals',
  path: '/manuals',
  getParentRoute: () => rootRouteImport,
} as any)
const CocktailsRoute = CocktailsRouteImport.update({
  id: '/cocktails',
  path: '/cocktails',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RulesRoute,
} as any)
const RecentIndexRoute = RecentIndexRouteImport.update({
  id: '/recent/',
  path: '/recent/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/qa/',
  path: '/qa/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsIndexRoute = ManualsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManualsRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeWorkIndexRoute = EmployeeWorkIndexRouteImport.update({
  id: '/employee-work/',
  path: '/employee-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLoginIndexRoute = EmployeeLoginIndexRouteImport.update({
  id: '/employee-login/',
  path: '/employee-login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CocktailsIndexRoute = CocktailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CocktailsRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const ManualsIdRoute = ManualsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ManualsRoute,
} as any)
const EmployeeWorkIdRoute = EmployeeWorkIdRouteImport.update({
  id: '/employee-work/$id',
  path: '/employee-work/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CocktailsIdRoute = CocktailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CocktailsRoute,
} as any)
const AboutIdRoute = AboutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AboutRoute,
} as any)
const RulesCategoryIdRoute = RulesCategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => RulesRoute,
} as any)
const ApiNotionImageBlockIdRoute = ApiNotionImageBlockIdRouteImport.update({
  id: '/api/notion-image/$blockId',
  path: '/api/notion-image/$blockId',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCategoryIdRoute = AboutCategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/cocktails': typeof CocktailsRouteWithChildren
  '/manuals': typeof ManualsRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/rules': typeof RulesRouteWithChildren
  '/about/$id': typeof AboutIdRoute
  '/cocktails/$id': typeof CocktailsIdRoute
  '/employee-work/$id': typeof EmployeeWorkIdRoute
  '/manuals/$id': typeof ManualsIdRoute
  '/about/': typeof AboutIndexRoute
  '/cocktails/': typeof CocktailsIndexRoute
  '/employee-login/': typeof EmployeeLoginIndexRoute
  '/employee-work/': typeof EmployeeWorkIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manuals/': typeof ManualsIndexRoute
  '/me/': typeof MeIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/qa/': typeof QaIndexRoute
  '/recent/': typeof RecentIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/about/category/$id': typeof AboutCategoryIdRoute
  '/api/notion-image/$blockId': typeof ApiNotionImageBlockIdRoute
  '/rules/category/$id': typeof RulesCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/$id': typeof AboutIdRoute
  '/cocktails/$id': typeof CocktailsIdRoute
  '/employee-work/$id': typeof EmployeeWorkIdRoute
  '/manuals/$id': typeof ManualsIdRoute
  '/about': typeof AboutIndexRoute
  '/cocktails': typeof CocktailsIndexRoute
  '/employee-login': typeof EmployeeLoginIndexRoute
  '/employee-work': typeof EmployeeWorkIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/login': typeof LoginIndexRoute
  '/manuals': typeof ManualsIndexRoute
  '/me': typeof MeIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/qa': typeof QaIndexRoute
  '/recent': typeof RecentIndexRoute
  '/rules': typeof RulesIndexRoute
  '/search': typeof SearchIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/about/category/$id': typeof AboutCategoryIdRoute
  '/api/notion-image/$blockId': typeof ApiNotionImageBlockIdRoute
  '/rules/category/$id': typeof RulesCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/cocktails': typeof CocktailsRouteWithChildren
  '/manuals': typeof ManualsRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/rules': typeof RulesRouteWithChildren
  '/about/$id': typeof AboutIdRoute
  '/cocktails/$id': typeof CocktailsIdRoute
  '/employee-work/$id': typeof EmployeeWorkIdRoute
  '/manuals/$id': typeof ManualsIdRoute
  '/about/': typeof AboutIndexRoute
  '/cocktails/': typeof CocktailsIndexRoute
  '/employee-login/': typeof EmployeeLoginIndexRoute
  '/employee-work/': typeof EmployeeWorkIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/manuals/': typeof ManualsIndexRoute
  '/me/': typeof MeIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/qa/': typeof QaIndexRoute
  '/recent/': typeof RecentIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/about/category/$id': typeof AboutCategoryIdRoute
  '/api/notion-image/$blockId': typeof ApiNotionImageBlockIdRoute
  '/rules/category/$id': typeof RulesCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cocktails'
    | '/manuals'
    | '/organization'
    | '/rules'
    | '/about/$id'
    | '/cocktails/$id'
    | '/employee-work/$id'
    | '/manuals/$id'
    | '/about/'
    | '/cocktails/'
    | '/employee-login/'
    | '/employee-work/'
    | '/favorites/'
    | '/login/'
    | '/manuals/'
    | '/me/'
    | '/organization/'
    | '/qa/'
    | '/recent/'
    | '/rules/'
    | '/search/'
    | '/updates/'
    | '/about/category/$id'
    | '/api/notion-image/$blockId'
    | '/rules/category/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/$id'
    | '/cocktails/$id'
    | '/employee-work/$id'
    | '/manuals/$id'
    | '/about'
    | '/cocktails'
    | '/employee-login'
    | '/employee-work'
    | '/favorites'
    | '/login'
    | '/manuals'
    | '/me'
    | '/organization'
    | '/qa'
    | '/recent'
    | '/rules'
    | '/search'
    | '/updates'
    | '/about/category/$id'
    | '/api/notion-image/$blockId'
    | '/rules/category/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cocktails'
    | '/manuals'
    | '/organization'
    | '/rules'
    | '/about/$id'
    | '/cocktails/$id'
    | '/employee-work/$id'
    | '/manuals/$id'
    | '/about/'
    | '/cocktails/'
    | '/employee-login/'
    | '/employee-work/'
    | '/favorites/'
    | '/login/'
    | '/manuals/'
    | '/me/'
    | '/organization/'
    | '/qa/'
    | '/recent/'
    | '/rules/'
    | '/search/'
    | '/updates/'
    | '/about/category/$id'
    | '/api/notion-image/$blockId'
    | '/rules/category/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CocktailsRoute: typeof CocktailsRouteWithChildren
  ManualsRoute: typeof ManualsRouteWithChildren
  OrganizationRoute: typeof OrganizationRouteWithChildren
  RulesRoute: typeof RulesRouteWithChildren
  EmployeeWorkIdRoute: typeof EmployeeWorkIdRoute
  EmployeeLoginIndexRoute: typeof EmployeeLoginIndexRoute
  EmployeeWorkIndexRoute: typeof EmployeeWorkIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  QaIndexRoute: typeof QaIndexRoute
  RecentIndexRoute: typeof RecentIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
  ApiNotionImageBlockIdRoute: typeof ApiNotionImageBlockIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals': {
      id: '/manuals'
      path: '/manuals'
      fullPath: '/manuals'
      preLoaderRoute: typeof ManualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocktails': {
      id: '/cocktails'
      path: '/cocktails'
      fullPath: '/cocktails'
      preLoaderRoute: typeof CocktailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof RulesRoute
    }
    '/recent/': {
      id: '/recent/'
      path: '/recent'
      fullPath: '/recent/'
      preLoaderRoute: typeof RecentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/qa'
      fullPath: '/qa/'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals/': {
      id: '/manuals/'
      path: '/'
      fullPath: '/manuals/'
      preLoaderRoute: typeof ManualsIndexRouteImport
      parentRoute: typeof ManualsRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-work/': {
      id: '/employee-work/'
      path: '/employee-work'
      fullPath: '/employee-work/'
      preLoaderRoute: typeof EmployeeWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-login/': {
      id: '/employee-login/'
      path: '/employee-login'
      fullPath: '/employee-login/'
      preLoaderRoute: typeof EmployeeLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocktails/': {
      id: '/cocktails/'
      path: '/'
      fullPath: '/cocktails/'
      preLoaderRoute: typeof CocktailsIndexRouteImport
      parentRoute: typeof CocktailsRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/manuals/$id': {
      id: '/manuals/$id'
      path: '/$id'
      fullPath: '/manuals/$id'
      preLoaderRoute: typeof ManualsIdRouteImport
      parentRoute: typeof ManualsRoute
    }
    '/employee-work/$id': {
      id: '/employee-work/$id'
      path: '/employee-work/$id'
      fullPath: '/employee-work/$id'
      preLoaderRoute: typeof EmployeeWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocktails/$id': {
      id: '/cocktails/$id'
      path: '/$id'
      fullPath: '/cocktails/$id'
      preLoaderRoute: typeof CocktailsIdRouteImport
      parentRoute: typeof CocktailsRoute
    }
    '/about/$id': {
      id: '/about/$id'
      path: '/$id'
      fullPath: '/about/$id'
      preLoaderRoute: typeof AboutIdRouteImport
      parentRoute: typeof AboutRoute
    }
    '/rules/category/$id': {
      id: '/rules/category/$id'
      path: '/category/$id'
      fullPath: '/rules/category/$id'
      preLoaderRoute: typeof RulesCategoryIdRouteImport
      parentRoute: typeof RulesRoute
    }
    '/api/notion-image/$blockId': {
      id: '/api/notion-image/$blockId'
      path: '/api/notion-image/$blockId'
      fullPath: '/api/notion-image/$blockId'
      preLoaderRoute: typeof ApiNotionImageBlockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/category/$id': {
      id: '/about/category/$id'
      path: '/category/$id'
      fullPath: '/about/category/$id'
      preLoaderRoute: typeof AboutCategoryIdRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutIdRoute: typeof AboutIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AboutCategoryIdRoute: typeof AboutCategoryIdRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutIdRoute: AboutIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  AboutCategoryIdRoute: AboutCategoryIdRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface CocktailsRouteChildren {
  CocktailsIdRoute: typeof CocktailsIdRoute
  CocktailsIndexRoute: typeof CocktailsIndexRoute
}

const CocktailsRouteChildren: CocktailsRouteChildren = {
  CocktailsIdRoute: CocktailsIdRoute,
  CocktailsIndexRoute: CocktailsIndexRoute,
}

const CocktailsRouteWithChildren = CocktailsRoute._addFileChildren(
  CocktailsRouteChildren,
)

interface ManualsRouteChildren {
  ManualsIdRoute: typeof ManualsIdRoute
  ManualsIndexRoute: typeof ManualsIndexRoute
}

const ManualsRouteChildren: ManualsRouteChildren = {
  ManualsIdRoute: ManualsIdRoute,
  ManualsIndexRoute: ManualsIndexRoute,
}

const ManualsRouteWithChildren =
  ManualsRoute._addFileChildren(ManualsRouteChildren)

interface OrganizationRouteChildren {
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

interface RulesRouteChildren {
  RulesIndexRoute: typeof RulesIndexRoute
  RulesCategoryIdRoute: typeof RulesCategoryIdRoute
}

const RulesRouteChildren: RulesRouteChildren = {
  RulesIndexRoute: RulesIndexRoute,
  RulesCategoryIdRoute: RulesCategoryIdRoute,
}

const RulesRouteWithChildren = RulesRoute._addFileChildren(RulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CocktailsRoute: CocktailsRouteWithChildren,
  ManualsRoute: ManualsRouteWithChildren,
  OrganizationRoute: OrganizationRouteWithChildren,
  RulesRoute: RulesRouteWithChildren,
  EmployeeWorkIdRoute: EmployeeWorkIdRoute,
  EmployeeLoginIndexRoute: EmployeeLoginIndexRoute,
  EmployeeWorkIndexRoute: EmployeeWorkIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MeIndexRoute: MeIndexRoute,
  QaIndexRoute: QaIndexRoute,
  RecentIndexRoute: RecentIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
  ApiNotionImageBlockIdRoute: ApiNotionImageBlockIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
